version: '3.9'
services:

  app:
    build:
      context: .
    logging:
      driver: fluentd
      options:
        "fluentd-address": "127.0.0.1:24224"  # This address is from the perspective of the Docker daemon
        "tag": "docker/{{.ImageName}}/{{.Name}}/{{.ID}}"  # https://docs.docker.com/config/containers/logging/log_tags/
    links:
      - fluentd
    restart: unless-stopped

  fluentd:
    build: ./fluentd
    environment: # used by fluent.conf
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
    - ./fluentd/conf:/fluentd/etc/
    ports:  # We need to expose these ports to the host so the Docker engine can log to it.
      - "24224:24224"
      - "24224:24224/udp"
    restart: unless-stopped
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.4.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"
    restart: unless-stopped

  kibana:
    image: kibana:8.4.0
    ports:
      - "5601:5601"
    restart: unless-stopped
    depends_on:
      - elasticsearch

networks:
  default:
    name: elastic
    external: true

# TODO ingest elastic user creds via env vars
# or gett elastic cert and copy to fluentd