version: '3.9'
services:
  app:
    build:
      context: .
    logging:
      driver: fluentd
      options:
        "fluentd-address": "127.0.0.1:24224"  # This address is from the perspective of the Docker daemon
        "tag": "docker/{{.ImageName}}/{{.Name}}/{{.ID}}"  # https://docs.docker.com/config/containers/logging/log_tags/
    links:
      - fluentd


  fluentd:
    build: ./fluentd
    volumes:
    - ./fluentd/conf:/fluentd/etc/
    ports:
      # We need to expose these ports to the host so the Docker engine can log to it.
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    depends_on:
      - elasticsearch


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
#    container_name: elasticsearch
#    environment:
#      # We are running ElasticSearch in single-node mode.
#      # Do we need to say this is not production ready?
#      - "discovery.type=single-node"
  kibana:
    image: kibana:8.4.0
    ports:
      - "127.0.0.1:5602:5601"
    depends_on:
      - elasticsearch

networks:
  default:
    name: elastic
    external: true

# TODO ingest elastic user creds via env vars
# or gett elastic cert and copy to fluentd