name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-image:
    name: Build ${{ matrix.image.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - {version: "3.9-slim-bookworm", suffix: ''}
          - {version: "3.10-slim-bookworm", suffix: '-py310'}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sebastianliebscher/fluentd-exchangerates
          flavor: |
            latest=false
            suffix=${{ matrix.image.suffix }}
          tags: |
            type=sha,prefix=,format=long
            type=ref,event=pr
            type=raw,value=master,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=pep440,pattern={{version}}
          labels: |
            org.opencontainers.image.authors=Sebastian Liebscher
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/sebastianliebscher/fluentd-exchangerates-cache:${{ github.ref_name }}
          cache-to: type=registry,ref=ghcr.io/sebastianliebscher/fluentd-exchangerates-cache:${{ github.ref_name }}
          build-args: |
            IMAGE=${{ matrix.image.version }}
